In [1]:
import pandas as pd
df = pd.read_csv('Resources/MUA_Find_Export.csv')
df.head()

,data.HRSA.gov – MUA Find,data.HRSA.gov – MUA Find.1,data.HRSA.gov – MUA Find.2,data.HRSA.gov – MUA Find.3,data.HRSA.gov – MUA Find.4,data.HRSA.gov – MUA Find.5,data.HRSA.gov – MUA Find.6,data.HRSA.gov – MUA Find.7,data.HRSA.gov – MUA Find.8,data.HRSA.gov – MUA Find.9,data.HRSA.gov – MUA Find.10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Discipline,MUA/P ID,Service Area Name,Designation Type,Primary State Name,County,Index of Medical Underservice Score,Status,Rural Status,Designation Date,Update Date
2,Primary Care,00001,Autauga County,Medically Underserved Area,Alabama,"Autauga County, AL",52.9,Designated,Non-Rural,01/01/1994,01/01/1994
3,NaN,Component State Name,Component County Name,Component Name,Component Type,Component GEOID,Component Rural Status,NaN,NaN,NaN,NaN
4,NaN,Alabama,Autauga,Autauga,Single County,01001,Partially Rural,NaN,NaN,NaN,NaN

In [2]:
#Rename Columns
df = df.rename(columns={"data.HRSA.gov – MUA Find":"Discipline",
 "data.HRSA.gov – MUA Find.1":"MUA/P_ID",
 "data.HRSA.gov – MUA Find.2":"Service_Area_Name",
 "data.HRSA.gov – MUA Find.3":"Designation_Type",
 "data.HRSA.gov – MUA Find.4":"Primary_State_Name",
 "data.HRSA.gov – MUA Find.5":"County",
 "data.HRSA.gov – MUA Find.6":"Index_of_Medical_Underservice_Score",
 "data.HRSA.gov – MUA Find.7":"Status",
 "data.HRSA.gov – MUA Find.8":"Rural_Status",
 "data.HRSA.gov – MUA Find.9":"Designation_Date",
 "data.HRSA.gov – MUA Find.10":"Update_Date"})
df.head()

,Discipline,MUA/P_ID,Service_Area_Name,Designation_Type,Primary_State_Name,County,Index_of_Medical_Underservice_Score,Status,Rural_Status,Designation_Date,Update_Date
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Discipline,MUA/P ID,Service Area Name,Designation Type,Primary State Name,County,Index of Medical Underservice Score,Status,Rural Status,Designation Date,Update Date
2,Primary Care,00001,Autauga County,Medically Underserved Area,Alabama,"Autauga County, AL",52.9,Designated,Non-Rural,01/01/1994,01/01/1994
3,NaN,Component State Name,Component County Name,Component Name,Component Type,Component GEOID,Component Rural Status,NaN,NaN,NaN,NaN
4,NaN,Alabama,Autauga,Autauga,Single County,01001,Partially Rural,NaN,NaN,NaN,NaN

In [3]:
#In the original file there are two rows between each line item with expanded data we dont need
df = df.dropna()
df.head()

,Discipline,MUA/P_ID,Service_Area_Name,Designation_Type,Primary_State_Name,County,Index_of_Medical_Underservice_Score,Status,Rural_Status,Designation_Date,Update_Date
1,Discipline,MUA/P ID,Service Area Name,Designation Type,Primary State Name,County,Index of Medical Underservice Score,Status,Rural Status,Designation Date,Update Date
2,Primary Care,00001,Autauga County,Medically Underserved Area,Alabama,"Autauga County, AL",52.9,Designated,Non-Rural,01/01/1994,01/01/1994
6,Primary Care,00002,Baldwin County,Medically Underserved Area,Alabama,"Baldwin County, AL",58.4,Designated,Partially Rural,01/01/1994,01/01/1994
10,Primary Care,00004,Bibb County,Medically Underserved Area,Alabama,"Bibb County, AL",47.7,Designated,Non-Rural,11/01/1978,11/01/1978
13,Primary Care,00005,Blounty County,Medically Underserved Area,Alabama,"Blount County, AL",56.1,Designated,Partially Rural,11/01/1978,11/01/1978

In [4]:
# Drop the first row since it's a duplicate of the headers and reset the index
df = df.drop([1], axis=0)
df = df.reset_index(drop=True)
df.head()

,Discipline,MUA/P_ID,Service_Area_Name,Designation_Type,Primary_State_Name,County,Index_of_Medical_Underservice_Score,Status,Rural_Status,Designation_Date,Update_Date
0,Primary Care,00001,Autauga County,Medically Underserved Area,Alabama,"Autauga County, AL",52.9,Designated,Non-Rural,01/01/1994,01/01/1994
1,Primary Care,00002,Baldwin County,Medically Underserved Area,Alabama,"Baldwin County, AL",58.4,Designated,Partially Rural,01/01/1994,01/01/1994
2,Primary Care,00004,Bibb County,Medically Underserved Area,Alabama,"Bibb County, AL",47.7,Designated,Non-Rural,11/01/1978,11/01/1978
3,Primary Care,00005,Blounty County,Medically Underserved Area,Alabama,"Blount County, AL",56.1,Designated,Partially Rural,11/01/1978,11/01/1978
4,Primary Care,00006,Bullock County,Medically Underserved Area,Alabama,"Bullock County, AL",61.7,Designated,Rural,11/01/1978,10/22/2012

In [5]:
# Drop Service Area Name because the county name is in "County" column.
    #"Service Area" column has other unwanted text or misspelled text.
# Drop MUA/P_ID because once the combined counties are split there will be duplicate ID
# Drop "Status" it creates duplicate counties
# Drop "Rural_Status" it creates duplicate counties
# Drop date columns because they are not needed
df.drop(['Discipline', 'MUA/P_ID','Service_Area_Name', 'Designation_Type', 'Status', 'Rural_Status', 'Designation_Date', 'Update_Date'], 1, inplace=True)
df.head()

C:\Users\cookr\AppData\Local\Temp/ipykernel_20296/1049777894.py:7: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df.drop(['Discipline', 'MUA/P_ID','Service_Area_Name', 'Designation_Type', 'Status', 'Rural_Status', 'Designation_Date', 'Update_Date'], 1, inplace=True)

  Primary_State_Name              County Index_of_Medical_Underservice_Score
0            Alabama  Autauga County, AL                                52.9
1            Alabama  Baldwin County, AL                                58.4
2            Alabama     Bibb County, AL                                47.7
3            Alabama   Blount County, AL                                56.1
4            Alabama  Bullock County, AL                                61.7

In [6]:
#Row count BEFORE splitting combined counties
print(df.shape)

(101, 3)

In [7]:
df = (df.set_index(df.columns.drop('County',1).tolist())
     .County.str.split('|', expand=True)
     .stack()
     .reset_index()
     .rename(columns={0:'County'})
     .loc[:, df.columns]
    )
df.head()
#One of the duplicate County rows was on line 29, df.head(33) to show the new rows

  Primary_State_Name              County Index_of_Medical_Underservice_Score
0            Alabama  Autauga County, AL                                52.9
1            Alabama  Baldwin County, AL                                58.4
2            Alabama     Bibb County, AL                                47.7
3            Alabama   Blount County, AL                                56.1
4            Alabama  Bullock County, AL                                61.7

In [8]:
#Row count AFTER splitting combined counties. 
    #In the Alabama data set there were 2 rows with multiple columns. The row count is now increased by 2
print(df.shape)

(103, 3)

In [9]:
df.dtypes

Primary_State_Name                     object
County                                 object
Index_of_Medical_Underservice_Score    object
dtype: object

In [10]:
# Change "Index_of_Medical_Underservice_Score" data type fro object to int
df['Index_of_Medical_Underservice_Score'] = df['Index_of_Medical_Underservice_Score'].astype(float).astype(int, errors='ignore')

In [11]:
df.dtypes

Primary_State_Name                     object
County                                 object
Index_of_Medical_Underservice_Score     int32
dtype: object

In [12]:
#Strip blank spaces before and after strings
df["County"] = df["County"].str.strip()
df["Primary_State_Name"] = df["Primary_State_Name"].str.strip()

In [13]:
# Get Average "Index_of_Medical_Underservice_Score" per "County"
mua_score_df = df.groupby('County', as_index=False)['Index_of_Medical_Underservice_Score'].mean()
mua_score_df.head()

               County  Index_of_Medical_Underservice_Score
0  Autauga County, AL                                 52.0
1  Baldwin County, AL                                 58.0
2  Barbour County, AL                                 61.0
3     Bibb County, AL                                 47.0
4   Blount County, AL                                 56.0

In [14]:
# Drop "Index_of_Medical_Underservice_Score" from original df
df.drop(['Index_of_Medical_Underservice_Score'], 1, inplace=True)
df.head()

C:\Users\cookr\AppData\Local\Temp/ipykernel_20296/4256881273.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df.drop(['Index_of_Medical_Underservice_Score'], 1, inplace=True)

  Primary_State_Name              County
0            Alabama  Autauga County, AL
1            Alabama  Baldwin County, AL
2            Alabama     Bibb County, AL
3            Alabama   Blount County, AL
4            Alabama  Bullock County, AL

In [15]:
# Drop duplicate counties
df = df.drop_duplicates()
df = df.drop([1], axis=0)
df = df.reset_index(drop=True)
df.head()

  Primary_State_Name              County
0            Alabama  Autauga County, AL
1            Alabama     Bibb County, AL
2            Alabama   Blount County, AL
3            Alabama  Bullock County, AL
4            Alabama  Calhoun County, AL

In [16]:
print(df.shape)

(68, 2)

In [17]:
df2_merged = pd.merge(df, mua_score_df)
df2_merged

   Primary_State_Name              County  Index_of_Medical_Underservice_Score
0             Alabama  Autauga County, AL                                 52.0
1             Alabama     Bibb County, AL                                 47.0
2             Alabama   Blount County, AL                                 56.0
3             Alabama  Bullock County, AL                                 61.0
4             Alabama  Calhoun County, AL                                 61.0
..                ...                 ...                                  ...
63            Alabama   Geneva County, AL                                 57.0
64            Alabama   Monroe County, AL                                 61.0
65            Alabama     Pike County, AL                                 60.0
66            Alabama   Walker County, AL                                 61.0
67            Alabama   Wilcox County, AL                                 51.0

[68 rows x 3 columns]

In [18]:
print(df2_merged.shape)

(68, 3)